---
kind: pipeline
name: RPM Build EL7

platform:
  os: linux
  arch: amd64

steps:
  - name: Build EL7
    image: rancher/dapper:v0.5.0
    commands:
      - dapper -f Dockerfile.centos7.dapper policy/centos7/scripts/build
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: Sign RPM EL7
    image: centos:7
    environment:
      PRIVATE_KEY:
        from_secret: private_key
      PRIVATE_KEY_PASS_PHRASE:
        from_secret: private_key_pass_phrase
      TESTING_PRIVATE_KEY:
        from_secret: testing_private_key
      TESTING_PRIVATE_KEY_PASS_PHRASE:
        from_secret: testing_private_key_pass_phrase
    commands:
      - policy/centos7/scripts/sign
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

  - name: Yum Repo Upload EL7
    image: centos:7
    environment:
      AWS_S3_BUCKET:
        from_secret: aws_s3_bucket
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      TESTING_AWS_S3_BUCKET:
        from_secret: testing_aws_s3_bucket
      TESTING_AWS_ACCESS_KEY_ID:
        from_secret: testing_aws_access_key_id
      TESTING_AWS_SECRET_ACCESS_KEY:
        from_secret: testing_aws_secret_access_key
    commands:
      - policy/centos7/scripts/upload-repo
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

  - name: GitHub Release EL7
    image: ibuildthecloud/github-release:v0.0.1
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      checksum:
        - sha256
      checksum_file: CHECKSUMsum-centos7-noarch.txt
      checksum_flatten: true
      files:
        - "dist/centos7/**/*.rpm"
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
---
kind: pipeline
name: RPM Build EL8

platform:
  os: linux
  arch: amd64

steps:
  - name: Build EL8
    image: rancher/dapper:v0.5.0
    commands:
      - dapper -f Dockerfile.centos8.dapper policy/centos8/scripts/build
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: Sign RPM EL8
    image: centos:7
    environment:
      PRIVATE_KEY:
        from_secret: private_key
      PRIVATE_KEY_PASS_PHRASE:
        from_secret: private_key_pass_phrase
      TESTING_PRIVATE_KEY:
        from_secret: testing_private_key
      TESTING_PRIVATE_KEY_PASS_PHRASE:
        from_secret: testing_private_key_pass_phrase
    commands:
      - policy/centos8/scripts/sign
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

  - name: Yum Repo Upload EL8
    image: centos:7
    environment:
      AWS_S3_BUCKET:
        from_secret: aws_s3_bucket
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      TESTING_AWS_S3_BUCKET:
        from_secret: testing_aws_s3_bucket
      TESTING_AWS_ACCESS_KEY_ID:
        from_secret: testing_aws_access_key_id
      TESTING_AWS_SECRET_ACCESS_KEY:
        from_secret: testing_aws_secret_access_key
    commands:
      - policy/centos8/scripts/upload-repo
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

  - name: GitHub Release EL8
    image: ibuildthecloud/github-release:v0.0.1
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      checksum:
        - sha256
      checksum_file: CHECKSUMsum-centos8-noarch.txt
      checksum_flatten: true
      files:
        - "dist/centos8/**/*.rpm"
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
---
kind: pipeline
name: RPM Build EL9

platform:
  os: linux
  arch: amd64

steps:
  - name: Build EL9
    image: rancher/dapper:v0.5.0
    commands:
      - dapper -f Dockerfile.centos9.dapper policy/centos9/scripts/build
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: Sign RPM EL9
    image: centos:7
    environment:
      PRIVATE_KEY:
        from_secret: private_key
      PRIVATE_KEY_PASS_PHRASE:
        from_secret: private_key_pass_phrase
      TESTING_PRIVATE_KEY:
        from_secret: testing_private_key
      TESTING_PRIVATE_KEY_PASS_PHRASE:
        from_secret: testing_private_key_pass_phrase
    commands:
      - policy/centos9/scripts/sign
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

  - name: Yum Repo Upload EL9
    image: centos:7
    environment:
      AWS_S3_BUCKET:
        from_secret: aws_s3_bucket
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      TESTING_AWS_S3_BUCKET:
        from_secret: testing_aws_s3_bucket
      TESTING_AWS_ACCESS_KEY_ID:
        from_secret: testing_aws_access_key_id
      TESTING_AWS_SECRET_ACCESS_KEY:
        from_secret: testing_aws_secret_access_key
    commands:
      - policy/centos9/scripts/upload-repo
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

  - name: GitHub Release EL9
    image: ibuildthecloud/github-release:v0.0.1
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      checksum:
        - sha256
      checksum_file: CHECKSUMsum-centos9-noarch.txt
      checksum_flatten: true
      files:
        - "dist/centos9/**/*.rpm"
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
---
kind: pipeline
name: RPM Build SLE

platform:
  os: linux
  arch: amd64

steps:
  - name: Build SLE
    image: rancher/dapper:v0.5.0
    commands:
      - dapper -f Dockerfile.microos.dapper policy/microos/scripts/build
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: Sign RPM SLE
    image: centos:7
    environment:
      PRIVATE_KEY:
        from_secret: private_key
      PRIVATE_KEY_PASS_PHRASE:
        from_secret: private_key_pass_phrase
      TESTING_PRIVATE_KEY:
        from_secret: testing_private_key
      TESTING_PRIVATE_KEY_PASS_PHRASE:
        from_secret: testing_private_key_pass_phrase
    commands:
      - policy/microos/scripts/sign
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

  - name: Yum Repo Upload SLE
    image: centos:7
    environment:
      AWS_S3_BUCKET:
        from_secret: aws_s3_bucket
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      TESTING_AWS_S3_BUCKET:
        from_secret: testing_aws_s3_bucket
      TESTING_AWS_ACCESS_KEY_ID:
        from_secret: testing_aws_access_key_id
      TESTING_AWS_SECRET_ACCESS_KEY:
        from_secret: testing_aws_secret_access_key
    commands:
      - policy/microos/scripts/upload-repo
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

  - name: GitHub Release SLE
    image: ibuildthecloud/github-release:v0.0.1
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      checksum:
        - sha256
      checksum_file: CHECKSUMsum-microos-noarch.txt
      checksum_flatten: true
      files:
        - "dist/microos/**/*.rpm"
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

---
kind: pipeline
name: RPM Build SLE Micro

platform:
  os: linux
  arch: amd64

steps:
  - name: Build SLE Micro
    image: rancher/dapper:v0.5.0
    commands:
      - dapper -f Dockerfile.slemicro.dapper policy/slemicro/scripts/build
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: Sign RPM SLE Micro
    image: centos:7
    environment:
      PRIVATE_KEY:
        from_secret: private_key
      PRIVATE_KEY_PASS_PHRASE:
        from_secret: private_key_pass_phrase
      TESTING_PRIVATE_KEY:
        from_secret: testing_private_key
      TESTING_PRIVATE_KEY_PASS_PHRASE:
        from_secret: testing_private_key_pass_phrase
    commands:
      - policy/slemicro/scripts/sign
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

  - name: Yum Repo Upload SLE Micro
    image: centos:7
    environment:
      AWS_S3_BUCKET:
        from_secret: aws_s3_bucket
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      TESTING_AWS_S3_BUCKET:
        from_secret: testing_aws_s3_bucket
      TESTING_AWS_ACCESS_KEY_ID:
        from_secret: testing_aws_access_key_id
      TESTING_AWS_SECRET_ACCESS_KEY:
        from_secret: testing_aws_secret_access_key
    commands:
      - policy/slemicro/scripts/upload-repo
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

  - name: GitHub Release SLE
    image: ibuildthecloud/github-release:v0.0.1
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      checksum:
        - sha256
      checksum_file: CHECKSUMsum-slemicro-noarch.txt
      checksum_flatten: true
      files:
        - "dist/slemicro/**/*.rpm"
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

---
kind: pipeline
name: RPM Build CoreOS

platform:
  os: linux
  arch: amd64

steps:
  - name: Build CoreOS
    image: rancher/dapper:v0.5.0
    commands:
      - dapper -f Dockerfile.coreos.dapper policy/coreos/scripts/build
    volumes:
      - name: docker
        path: /var/run/docker.sock

  - name: Sign RPM CoreOS
    image: centos:7
    environment:
      PRIVATE_KEY:
        from_secret: private_key
      PRIVATE_KEY_PASS_PHRASE:
        from_secret: private_key_pass_phrase
      TESTING_PRIVATE_KEY:
        from_secret: testing_private_key
      TESTING_PRIVATE_KEY_PASS_PHRASE:
        from_secret: testing_private_key_pass_phrase
    commands:
      - policy/coreos/scripts/sign
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

  - name: Yum Repo Upload CoreOS
    image: centos:7
    environment:
      AWS_S3_BUCKET:
        from_secret: aws_s3_bucket
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      TESTING_AWS_S3_BUCKET:
        from_secret: testing_aws_s3_bucket
      TESTING_AWS_ACCESS_KEY_ID:
        from_secret: testing_aws_access_key_id
      TESTING_AWS_SECRET_ACCESS_KEY:
        from_secret: testing_aws_secret_access_key
    commands:
      - policy/coreos/scripts/upload-repo
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

  - name: GitHub Release CoreOS
    image: ibuildthecloud/github-release:v0.0.1
    settings:
      api_key:
        from_secret: github_token
      prerelease: true
      checksum:
        - sha256
      checksum_file: CHECKSUMsum-coreos-noarch.txt
      checksum_flatten: true
      files:
        - "dist/coreos/**/*.rpm"
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock