FROM rockylinux:8 AS build

RUN yum install -y epel-release \
 && yum install -y container-selinux git rpm-build selinux-policy-devel yum-utils pinentry python2-pip ca-certificates

ENV SOURCE=/source

WORKDIR ${SOURCE}

COPY . .

ARG TAG
ARG SCRIPT=build

RUN ${SOURCE}/policy/centos8/scripts/entry "${SCRIPT}"

FROM scratch AS result
ENV SOURCE=/source

COPY --from=build ${SOURCE}/dist /dist

