#!/bin/bash
set -e -x

dnf install -y epel-release wget

dnf install -y python3 python3-pip python3-devel \
  rpm-sign expect git

dnf install -y ca-certificates createrepo_c

pip install --upgrade boto3 pexpect

pushd $(dirname $0)/..
. ./scripts/version
popd

cat <<\EOF >~/.rpmmacros
%_signature gpg
%_gpg_name ci@rancher.com
%__gpg_sign_cmd %{__gpg} gpg --force-v3-sigs --batch --verbose --no-armor --passphrase-fd 3 --no-secmem-warning -u "%{_gpg_name}" -sbo %{__signature_filename} --digest-algo sha256 %{__plaintext_filename}
%_source_filedigest_algorithm 8
%_binary_filedigest_algorithm 8
EOF

if [ -z "$RPM_CHANNEL" ]; then
  echo "RPM_PATH not defined, failing rpm upload"
  exit 1
fi

TARGET_S3_PATH="rke2/$RPM_CHANNEL/common/centos/7/noarch"
TARGET_SOURCE_S3_PATH="rke2/$RPM_CHANNEL/common/centos/7/source"

case "$RPM_CHANNEL" in
"testing")
  export PRIVATE_KEY_PASS_PHRASE=$TESTING_PRIVATE_KEY_PASS_PHRASE
  if ! grep "BEGIN PGP PRIVATE KEY BLOCK" <<<"$TESTING_PRIVATE_KEY"; then
    echo "TESTING_PRIVATE_KEY not defined, failing rpm sign"
    exit 1
  fi
  gpg --import - <<<"$TESTING_PRIVATE_KEY"
  if [ -z "$TESTING_AWS_S3_BUCKET" ]; then
    echo "TESTING_AWS_S3_BUCKET not defined, failing rpm upload"
    exit 1
  fi
  if [ -z "$TESTING_AWS_ACCESS_KEY_ID" ]; then
    echo "TESTING_AWS_ACCESS_KEY_ID not defined, failing rpm upload"
    exit 1
  fi
  if [ -z "$TESTING_AWS_SECRET_ACCESS_KEY" ]; then
    echo "TESTING_AWS_SECRET_ACCESS_KEY not defined, failing rpm upload"
    exit 1
  fi
  export AWS_ACCESS_KEY_ID=$TESTING_AWS_ACCESS_KEY_ID
  export AWS_SECRET_ACCESS_KEY=$TESTING_AWS_SECRET_ACCESS_KEY
  export AWS_S3_BUCKET=$TESTING_AWS_S3_BUCKET
  ;;

"latest" | "stable")
  if ! grep "BEGIN PGP PRIVATE KEY BLOCK" <<<"$PRIVATE_KEY"; then
    echo "PRIVATE_KEY not defined, failing rpm sign"
    exit 1
  fi
  gpg --import - <<<"$PRIVATE_KEY"
  if [ -z "$AWS_S3_BUCKET" ]; then
    echo "AWS_S3_BUCKET not defined, failing rpm upload"
    exit 1
  fi
  if [ -z "$AWS_ACCESS_KEY_ID" ]; then
    echo "AWS_ACCESS_KEY_ID not defined, failing rpm upload"
    exit 1
  fi
  if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
    echo "AWS_SECRET_ACCESS_KEY not defined, failing rpm upload"
    exit 1
  fi
  ;;
*)
  echo "RPM_CHANNEL $RPM_CHANNEL does not match one of: [testing, latest, stable]"
  exit 1
  ;;
esac

wget https://raw.githubusercontent.com/rancher/ecm-distro-tools/master/bin/rpm_tooling
chmod +x rpm_tooling
mv ./rpm_tooling /usr/bin

rpm_tooling --bucket $AWS_S3_BUCKET/$TARGET_S3_PATH --region us-east-1 --sign --sign-pass $PRIVATE_KEY_PASS_PHRASE --aws-access-key $AWS_ACCESS_KEY_ID --aws-secret-key $AWS_ACCESS_KEY_ID dist/centos7/noarch/rke2-*.rpm
rpm_tooling --bucket $AWS_S3_BUCKET/$TARGET_SOURCE_S3_PATH --region us-east-1 --sign --sign-pass $PRIVATE_KEY_PASS_PHRASE --aws-access-key $AWS_ACCESS_KEY_ID --aws-secret-key $AWS_ACCESS_KEY_ID dist/centos7/source/rke2-*src.rpm
