#!/bin/bash
set -ex


cd $(dirname $0)/..
ls -la
pwd

CHECKSUM_DIR=${CHECKSUM_DIR:-./dist/centos7/noarch/}
CHECKSUM_FILE=${CHECKSUM_FILE:-CHECKSUMsum-centos7-noarch.txt}
DEST_DIR=${DEST_DIR:-${CHECKSUM_DIR}}

sumfile="${DEST_DIR}/${CHECKSUM_FILE}"

touch "${sumfile}"

files=$(ls ${CHECKSUM_DIR} | grep -v "sha256sum")
for file in ${files}; do
  sha256sum "${CHECKSUM_DIR}/${file}" | sed "s;$(dirname ${CHECKSUM_DIR}/${file})/;;g" >> "${sumfile}"
done

cat "${sumfile}"